export const USER_ERROR_CODES = {
  EMAIL_INVALID: 'EMAIL_INVALID',

  PASSWORD_INVALID: 'PASSWORD_INVALID',
  PASSWORD_LENGTH: 'PASSWORD_LENGTH',
  PASSWORD_LOWERCASE_LETTER: 'PASSWORD_LOWERCASE_LETTER',
  PASSWORD_UPPERCASE_LETTER: 'PASSWORD_UPPERCASE_LETTER',
  PASSWORD_NUMBER: 'PASSWORD_NUMBER',
  PASSWORD_SYMBOL: 'PASSWORD_SYMBOL',

  FIRST_NAME_INVALID: 'FIRST_NAME_INVALID',
  FIRST_NAME_LENGTH: 'FIRST_NAME_LENGTH',

  LAST_NAME_INVALID: 'LAST_NAME_INVALID',
  LAST_NAME_LENGTH: 'LAST_NAME_LENGTH',
} as const;
